<center><br><font size=10>NumPy Tutorial</font><br>
<br><br>
<b>Data Analysis</b>
<br>Digital Sciences for Hi-Tech - Tel Aviv University
<br>
Author: Yehonatan Bar Moshe 
<br>

<br>
In this notebook, we'll learn the basics of data analysis with the Python NumPy library.
<tr><td><img src="https://upload.wikimedia.org/wikipedia/commons/3/31/NumPy_logo_2020.svg" width=300></td><td>

# Table of Contents
* [NumPy Array Attributes and Creation](#NumPy-Array---Attributes-and-Creation)
* [NumPy Array - Accessing Data](#NumPy-Array---Accessing-Data)
* [NumPy Array - Arrays Math](#NumPy-Array---Arrays-Math)
* [NumPy Array - Array Analysis Functions](#NumPy-Array---Array-Analysis-Functions)

**Import Library**

In [ ]:
import numpy as np

# NumPy Array - Attributes and Creation 

## N-Dimensional Array
**The MOST IMPORTANT NumPy object**
<br><br>
**Definition:**
<br>
Nd-arrays are the core data structure of NumPy.
<br>
They are **multi-dimensional**, **homogeneous** arrays of **fixed-size** items.
<br><br>

In [ ]:
array_1d = np.array([1,2,3,4,5,6,7,8])
array_1d

**Main Attributes**:
- Shape: Tuple indicating the size of each dimension.
- Size: Total number of elements in the array.
- Dimensions (ndim): Number of dimensions (axes) of the array.
- Data Type (dtype): Type of elements stored in the array.

In [ ]:
array = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15]])
print(array)

In [ ]:
print("Shape:", array.shape)
print("Size:", array.size)
print("Dimensions:", array.ndim)
print("Data Type:", array.dtype)

### N-dimensional Arrays creation
Creating an Array can be done in one of several ways.
<br>
Useful examples:
- Using a list of numbers
- Using nested list of numbers
- Using built-in functions
- Reshaping an existing array
- From CSV file

**Using a list of numbers**

In [ ]:
# From a list of numbers
array_from_list = np.array([1, 2, 3, 4, 5])
print(array_from_list)

**Using a nested list of numbers**

In [ ]:
# From a nested list of numbers
array_from_nested_list = np.array([[1, 2, 3], [4, 5,6], [7,8,9]])
print(array_from_nested_list)

**Using built-in functions**

In [ ]:
# Create an array filled with zeros.
zeros_array = np.zeros((3, 4))  # (3,4) Shaped array of zeros
print("zeros_array")
print(zeros_array)
print("----------------------------------------------")

# Create an array filled with a specified value.
full_array = np.full((2, 2), 7)  # (2,2) Shaped array filled with the number 7
print("full_array")
print(full_array)
print("----------------------------------------------")

# Create an array with a range of values.
range_array = np.arange(0, 30, 2)  # Array with values from 0 to 10 with a step of 2
print("range_array")
print(range_array)
print("----------------------------------------------")

# Create an array with a specified number of evenly spaced values over a specified interval.
linspace_array = np.linspace(0, 1, 5)  # Array with 5 values evenly spaced between 0 and 1
print("linspace_array")
print(linspace_array)
print("----------------------------------------------")

# Create an array with random values between 0 and 1.
random_array = np.random.uniform(0,1,(2,2))  # (2,2) Shaped array with random values between 0 and 1
print("random_array")
print(random_array)


**Reshaping an existing array**

In [ ]:
# Reshaping an existing array
original_array = np.arange(15)  # Array with values from 0 to 5
reshaped_array = original_array.reshape((5, 3))  # Reshape to 5x3 array
print(reshaped_array)

**From CSV file**

In [ ]:
# Create an array from a CSV file
array_from_csv = np.genfromtxt('numpy_data.csv', delimiter=',').astype('int32') # the default type is float, astype('int32') will change the type to integer  
print(array_from_csv)

# NumPy Array - Accessing Data

### N-dimensional Arrays creation
Accessing data in a NumPy array can be done in various ways, Each one has different uses:
<br>
Useful examples:
- Indexing
- Fancy Indexing
- Slicing
- Boolean Masking
<br><br>
Note: In the following examples we will use 2D Arrays because they are the most useful for the purpose of our course

**Indexing**
<br>
Indexing in an array allows us to access individual elements by specifying their row and column indices.

In [ ]:
# Create a 2D array
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("array_2d:")
print(array_2d)
print("----------------------------------------------")


# Access the element at row 1, column 2
element = array_2d[1, 2]
print("the element at row 1, column 2:")
print(element)

**Fancy Indexing**
<br>
Fancy indexing allows us to access specific elements by using arrays of row and column indices.
<br>
With Fancy indexing we will construct a 1D arrays using the data from another array

In [ ]:
print("array_2d:")
print(array_2d)
print("----------------------------------------------")

# Construct an array of the elements at (0, 0), (1, 1), (1,2) and (2, 2) using Fancy Indexing:
fancy_indexed_elements_array = array_2d[[0, 1, 1, 2], [0, 1, 2, 2]]
print("fancy_indexed_elements_array:")
print(fancy_indexed_elements_array)
print("----------------------------------------------")

# Construct an array of the elements at (0, 0), (1, 1), (1,2) and (2, 2) using Indexing:
indexed_elements_array = np.array([array_2d[0, 0], array_2d[1, 1], array_2d[1,2], array_2d[2, 2]])
print("indexed_elements_array:")
print(indexed_elements_array)

**Slicing**
<br>
Slicing allows us to access a subarray by specifying a range of rows and columns.

In [ ]:
print("array_2d:")
print(array_2d)
print("----------------------------------------------")

# Access the first two rows and all columns
sub_array_1 = array_2d[:2, :]
print("sub_array_1:")
print(sub_array_1)
print("----------------------------------------------")

# Access all rows and the first two columns
sub_array_2 = array_2d[:, :2]
print("sub_array_2:")
print(sub_array_2)
print("----------------------------------------------")

# Access the last two rows and last two columns
sub_array_3 = array_2d[1:, 1:]
print("sub_array_3")
print(sub_array_3)
print("----------------------------------------------")

# Access the last two rows and last two columns
sub_array_3 = array_2d[-2:, -1:]
print("sub_array_3")
print(sub_array_3)
print("----------------------------------------------")

In [ ]:
# Larger shape example:
print("array_from_csv:")
print(array_from_csv)
print("shape:")
print(array_from_csv.shape)
print("----------------------------------------------")

sub_array_4 = array_from_csv[1:4, 2:-1]
print("sub_array_4:")
print(sub_array_4)

In [ ]:
# Access the last two rows and last two columns
subarray = array_2d[-2:, -2:]
print(subarray)
# Output:
# [[5 6]
#  [8 9]]

**Boolean Masking**
<br>
Boolean Masking allows us to access elements that meet a specific condition.
<br>
With Boolean Masking we will construct a 1D arrays using the data from another array

In [ ]:
print("array_2d:")
print(array_2d)
print("----------------------------------------------")

# what is a Boolean Mask?
mask_2d = array_2d < 5
print("Boolean Mask:")
print(mask_2d)
print("----------------------------------------------")

masked_array = array_2d[mask_2d]
print("masked_array:")
print(masked_array)

# NumPy Array - Arrays Math

**Array Math**
<br>
NumPy allows a variety of mathematical operations on arrays and between arrays, including element-wise operations, broadcasting, and matrix operations.
<br><br>
In our course we will focuse only on element-wise operation and operations between arrays with the same shape.

**Transpose**
<br>
Rows become columns, and columns become rows

In [ ]:
print("original array")
print(array_from_csv)
print("----------------------------------------------")

# Transpose the array using np.transpose
transposed_array = np.transpose(array_from_csv)
print("Transposed array using np.transpose:\n", transposed_array)

**element-wise operations**
<br>
summation, subtraction, multiplication, division, powers and round. There are many more!

In [ ]:
array = np.linspace(1, 20,50).reshape(10,5)
print("the original array:")
print(array)
print("----------------------------------------------")

added_values = np.add(array,3)
print("added values:")
print(added_values)
print("----------------------------------------------")

subtracted_values = np.subtract(array,10)
print("subtracted values:")
print(subtracted_values)
print("----------------------------------------------")

multiplyed_values = np.multiply(array,5)
print("multiplyed values:")
print(multiplyed_values)
print("----------------------------------------------")

divided_values = np.divide(array,10)
print("divided values:")
print(divided_values)
print("----------------------------------------------")

powered_values = np.power(array, 0.5) #this is a square root
print("powered_values:")
print(powered_values)
print("----------------------------------------------")



In [ ]:
print("the original array:")
print(array)
print("----------------------------------------------")

rounded_values = np.round(array) #rounding to the nearest whole value
print("rounded values:")
print(rounded_values)
print("----------------------------------------------")

floor_values = np.floor(array) #rounding down
print("values rounded down:")
print(floor_values)
print("----------------------------------------------")

cail_values = np.ceil(array) #rounding up
print("values rounded up:")
print(cail_values)
print("----------------------------------------------")

rounded_3_decimal_places = np.round(array,3) # rounding to 3 decimal places
print("rounded 3 decimal places values:")
print(rounded_3_decimal_places)

**Element-wise Summation between arrays**

In [ ]:
# summation

x = np.array([[2,4,6,8,10],[3,6,9,12,15]])
y = np.array([[1,2,3,4,5],[3,3,3,3,3]])
print("The array x:")
print(x)
print("----------------------------------------------")
print("The array y:")
print(y)
print("----------------------------------------------")

# Elementwise summation; both produce the same output:
res1 = x + y
res2 = np.add(x, y)

print("The result array of x + y:")
print(res1)
print("----------------------------------------------")

print("The result array of np.add(x, y):")
print(res2)

**Element-wise Subtraction between arrays**

In [ ]:
# Subtraction

print("The array x:")
print(x)
print("----------------------------------------------")
print("The array y:")
print(y)
print("----------------------------------------------")

# Elementwise Subtraction; both produce the same output:
res3 = x - y
res4 = np.subtract(x, y)

print("The result array of x - y:")
print(res3)
print("----------------------------------------------")

print("The result array of np.subtract(x, y):")
print(res4)

**Element-wise Multiplication between arrays**

In [ ]:
print("The array x:")
print(x)
print("----------------------------------------------")
print("The array y:")
print(y)
print("----------------------------------------------")
# Elementwise multiplication; both produce the same output:

res5 = x * y
res6 = np.multiply(x, y)

print("The result array of x * y:")
print(res5)
print("----------------------------------------------")

print("The result array of np.multiply(x, y):")
print(res6)

**Element-wise Division between arrays**

In [ ]:
# division

print("The array x:")
print(x)
print("----------------------------------------------")
print("The array y:")
print(y)
print("----------------------------------------------")
# Elementwise division; both produce the same output:

res7 = x + y
res8 = np.divide(x, y)

print("The result array of x / y:")
print(res7)
print("----------------------------------------------")

print("The result array of np.divide(x, y):")
print(res8)

In [ ]:
# Create a 2D array
array_2d = np.array([[1, 2, 3], [4, 5, 6]])

# Apply square root function element-wise
sqrt_array = np.sqrt(array_2d)
print("Square root element-wise:\n", sqrt_array)
# Output:
# [[1.         1.41421356 1.73205081]
#  [2.         2.23606798 2.44948974]]

# Apply exponential function element-wise
exp_array = np.exp(array_2d)
print("Exponential element-wise:\n", exp_array)
# Output:
# [[  2.71828183   7.3890561   20.08553692]
#  [ 54.59815003 148.4131591  403.42879349]]

# NumPy Array - Array Analysis Functions

**Mean**

In [ ]:
print("the original array:")
print(array_from_csv)
print("----------------------------------------------")

# Calculate the mean of all elements
mean_all = np.mean(array_from_csv)
print("Mean of all elements:", mean_all)

# Calculate the mean along rows (axis=0) and columns (axis=1)
mean_rows = np.mean(array_from_csv, axis=0)
mean_columns = np.mean(array_from_csv, axis=1)
print("Mean along rows:", mean_rows)
print("Mean along columns:", mean_columns)

**Median**

In [ ]:
print("the original array:")
print(array_from_csv)
print("----------------------------------------------")

# Calculate the median of all elements
median_all = np.median(array_from_csv)
print("Median of all elements:", median_all)

# Calculate the median along rows (axis=0) and columns (axis=1)
median_rows = np.median(array_from_csv, axis=0)
median_columns = np.median(array_from_csv, axis=1)
print("Median along rows:", median_rows)
print("Median along columns:", median_columns)

**Percentiles**

In [ ]:
print("the original array:")
print(array_from_csv)
print("----------------------------------------------")

# Calculate the 25th, 50th, and 75th percentiles of all elements
percentile_25 = np.percentile(array_from_csv, 25)
percentile_50 = np.percentile(array_from_csv, 50)
percentile_75 = np.percentile(array_from_csv, 75)
print("25th percentile:", percentile_25)
print("50th percentile (median):", percentile_50)
print("75th percentile:", percentile_75)

# Calculate percentiles along rows (axis=0) and columns (axis=1)
percentile_25_rows = np.percentile(array_2d, 25, axis=0)
percentile_75_columns = np.percentile(array_2d, 75, axis=1)
print("25th percentile along rows:", percentile_25_rows)
print("75th percentile along columns:", percentile_75_columns)

**Standard Deviation and Variance**

In [ ]:
print("the original array:")
print(array_from_csv)
print("----------------------------------------------")

std_all = np.std(array_from_csv)
print("Standard deviation of a**Percentiles**ll elements:", std_all)

# Calculate the variance of all elements
variance_all = np.var(array_from_csv)
print("Variance of all elements:", variance_all)

# Calculate standard deviation and variance along rows (axis=0) and columns (axis=1)
std_rows = np.std(array_from_csv, axis=0)
variance_columns = np.var(array_from_csv, axis=1)
print("Standard deviation along rows:", std_rows)
print("Variance along columns:", variance_columns)

**Sum, Min, and Max**

In [ ]:
print("the original array:")
print(array_from_csv)
print("----------------------------------------------")

# Calculate the sum of all elements
sum_all = np.sum(array_from_csv)
print("Sum of all elements:", sum_all)

# Calculate the minimum and maximum of all elements
min_all = np.min(array_from_csv)
max_all = np.max(array_from_csv)
print("Minimum of all elements:", min_all)
print("Maximum of all elements:", max_all)

# Calculate sum, min, and max along rows (axis=0) and columns (axis=1)
sum_rows = np.sum(array_from_csv, axis=0)
min_columns = np.min(array_from_csv, axis=1)
max_columns = np.max(array_from_csv, axis=1)
print("Sum along rows:", sum_rows)
print("Minimum along columns:", min_columns)
print("Maximum along columns:", max_columns)